### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by ts33** [Tanbouz/codepipeline-artifact-merge#1]
Hi @Tanbouz! I've just checked out the repo and made a test for the `mergeArtifacts` method. If you could allow me access to this repo, I can push my branch and you could review it!

**Comment by Tanbouz** [comment]
Hello @ts33 

Can you please push to a fork then create a pull request here.

I apologize for lack of test coverage, thank you!

**Comment by ts33** [comment]
sure @Tanbouz, its [here](https://github.com/Tanbouz/codepipeline-artifact-merge/pull/2)
